In [1]:
import numpy as np
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print("Original Array:")
print(arr)
print("\nAccessing Elements:")
print("Element at [0][1]:", arr[0][1])
print("Element at [2][2]:", arr[2][2])
print("\nMathematical Operations:")
print("Addition:", arr[0][0] + arr[1][1])
print("Subtraction:", arr[2][2] - arr[0][0])
print("Multiplication:", arr[1][0] * arr[0][2])
print("Division:", arr[2][1] / arr[1][1])
print("\n1. Shape:", arr.shape)
print("2. Size:", arr.size)
print("3. Dimensions (ndim):", arr.ndim)
print("4. Data Type (dtype):", arr.dtype)
print("5. Sum:", np.sum(arr))
print("6. Mean:", np.mean(arr))
print("7. Maximum:", np.max(arr))
print("8. Minimum:", np.min(arr))
print("9. Standard Deviation:", np.std(arr))
print("10. Transpose:\n", arr.T)
print("11. Reshape (1x9):\n", arr.reshape(1, 9))
print("12. Flatten:\n", arr.flatten())
print("13. Sort:\n", np.sort(arr))
print("14. Square Root:\n", np.sqrt(arr))
print("15. Exponential:\n", np.exp(arr))
print("16. Unique Values:", np.unique(arr))
print("17. Cumulative Sum:\n", np.cumsum(arr))
print("18. Product of Elements:", np.prod(arr))
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("\nSecond Array:")
print(arr2)
print("\nArray Addition:\n", np.add(arr, arr2))
print("\nArray Subtraction:\n", np.subtract(arr, arr2))
print("\nArray Multiplication:\n", np.multiply(arr, arr2))
print("\nArray Division:\n", np.divide(arr, arr2))
print("\nMatrix Multiplication:")
print(np.dot(arr, arr2))
print("\nProgram Completed Successfully!")

Original Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Accessing Elements:
Element at [0][1]: 20
Element at [2][2]: 90

Mathematical Operations:
Addition: 60
Subtraction: 80
Multiplication: 1200
Division: 1.6

1. Shape: (3, 3)
2. Size: 9
3. Dimensions (ndim): 2
4. Data Type (dtype): int64
5. Sum: 450
6. Mean: 50.0
7. Maximum: 90
8. Minimum: 10
9. Standard Deviation: 25.81988897471611
10. Transpose:
 [[10 40 70]
 [20 50 80]
 [30 60 90]]
11. Reshape (1x9):
 [[10 20 30 40 50 60 70 80 90]]
12. Flatten:
 [10 20 30 40 50 60 70 80 90]
13. Sort:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
14. Square Root:
 [[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]
 [8.36660027 8.94427191 9.48683298]]
15. Exponential:
 [[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]
 [2.51543867e+30 5.54062238e+34 1.22040329e+39]]
16. Unique Values: [10 20 30 40 50 60 70 80 90]
17. Cumulative Sum:
 [ 10  30  60 100 150 210 280 360 450]
18. Product of Element